#!/bin/bash

if [ -d bats ]
then
  ( 
    cd bats
    git pull
  )
else
  git clone https://github.com/sstephenson/bats.git 
fi

if [ -d rbenv ]
then
  ( 
    cd rbenv
    git pull
  )
else
  git clone https://github.com/sstephenson/rbenv.git
fi

exec bats/bin/bats test
